In [3]:
import numpy as np

In [10]:
1-->
mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.array([[6,5,4], [3,2,1]])

print(mat1+mat2)

[[7 7 7]
 [7 7 7]]


In [8]:
2-->

mat2 = np.array([[6,5,4], [3,2,1]])

print(mat1*mat2)

[[ 6 10 12]
 [12 10  6]]


In [9]:
3-->

mat1 = np.array([[1,2,3], [4,5,6]])
print(mat1.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [14]:
4-->

words= ['box','peg','jug','mug']

words.sort()
print(words)

['box', 'jug', 'mug', 'peg']


In [16]:
5-->
string = 'my name is saichandraprasad,'
string.replace(',','')

'my name is saichandraprasad'